### ISSUE TITLE
Implement rules DSL/system

### ISSUE THREAD

**Issue by arusahni** [arusahni/klaxer#2]
We need to be able to allow users to define routing and filtering rules.  The equivalent Python:

```python
if 'error' in alert.message:
    return Severity.CRITICAL if 'error'
elif 'warning' in alert.message:
    return Severity.WARNING
else: 
    return None
```

Similarly, for routing:

```python
if alert.service == 'sensu' and 'hgtd' in alert.message:
   return '#hgtd'
```

And for enriching:

```python
if 'keepalive' in alert.message:
    return {'message': f'@deborah {alert.message}'}
```

We may not be able to hit all the edge cases, and that's fine. Part of this task will require identifying useful transforms and tests.

**Comment by dbernard** [comment]
Looking for some initial feedback as I start hacking this. So far I've come up with some initial config designs to start with in the form of a `klaxer.yml` file that is parsed on startup. Ideally later on this would be tweakable via the API.

Here is the initial proof of concept:

```yaml
classification:
    # Classify Service1 alerts
    - service: "Service1"
      critical: ["error", "failure"]
      warning: ["warning"]
    # Classify Service2 alerts
    - service: "Service2"
      critical: ["error"]

exclusion:
    # Exclude "keepalive" alerts from Service1
    - service: "Service1"
      message: "keepalive"
    # Exclude EVERYTHING from Service3
    - service: "Service3"

enrichment:
    # Enrich Service1 alerts where "testing" appears in the message with the result string
    - service: "Service1"
      message: "testing"
      result: "@dylan {} (enrichment added, have a :beer:)"

routes:
    # Route all Service2 alerts to the Klaxer channel
    - service: "Service2"
      result: "#klaxer"
```

This allows a separation of rule sets for different services. Thoughts?

I'm currently working out the logic required to parse and build the rule sets. Should end up closely mirroring the current `klaxer/config.py` process - building out collections of lambda functions to run alerts against.

**Comment by oxhacks** [comment]
@dbernard are the names of this rule sets meaningful (like, `routes` or `enrichment`)? This is more or less exactly what I had in mind. I was thinking YAML blocks per source - maybe something like this.

```yaml
sensu_things:
  # Process items from Sensu
  - service: "Sensu"
    levels:
    # map our internal levels to what Sensu says they are
    - warning: 'warning'
    - critical: 'broken'
    - routine: 'boring'
    enrichment: "@dylan {message} (this message is enriched)"
    channel: "#dmesg"
```

I think is largely what you're expressing, but just putting my thoughts on paper.

**Comment by arusahni** [comment]
I think I'm ultimately hoping for some unicorn of a solution that allows us to keep the versatility of scripting while providing us with the safety of plain text.

That's of course a hard problem. I do think I like the inversion @jaykwon's solution brings, as it fits what seems to be the general use-case of "oh hey, I have a new service I want to manage with Klaxer, let's configure it!"

**Comment by dbernard** [comment]
I agree, the ideal solution is probably a few iterations further away from **whatever** our first stab is, but this is looking promising.

The rule sets as they are right now are trying to capture each of the main "configurations" we have implemented now in `klaxer/config.py`, while keeping them as modular as possible. It might be TOO modular (to the point of being confusing to update).

One key in flexibility is different workflows for the same service - am I correct in thinking this is something we should expect?

Ex:

```yaml
sensu_devs:
  # Process items from Sensu FOR DEVELOPERS
  - service: "Sensu"
    levels:
    # map our internal levels to what Sensu says they are
    - warning: 'warning'
    - critical: 'broken'
    - routine: 'boring'
    enrichment: "@dylan {message} (this message is enriched)"
    channel: "#dmesg"

sensu_customers:
  # Process items from Sensu FOR CUSTOMERS
  - service: "Sensu"
    levels:
    # map our internal levels to what Sensu says they are
    - warning: 'warning'
    - critical: 'maintenance'
    - routine: 'event'
    enrichment: "@here {message}"
    channel: "#dmesg-customers"
```
